INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('1', '1', 'Port Wilsontown');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('2', '2', 'North Jeanie');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('3', '3', 'Hesselside');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('4', '4', 'Iciehaven');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('5', '5', 'East Abdulhaven');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('6', '6', 'Port Earline');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('7', '7', 'Titochester');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('8', '8', 'East Delphia');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('9', '9', 'Morarville');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('10', '10', 'New Wiltonhaven');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('11', '11', 'South Mark');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('12', '12', 'Justineview');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('13', '13', 'Milanchester');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('14', '14', 'Austynville');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('15', '15', 'East Heavenbury');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('16', '16', 'Fridatown');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('17', '17', 'Port Kiptown');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('18', '18', 'Aliyaton');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('19', '19', 'South Dana');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('20', '20', 'Prohaskafurt');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('21', '1', 'Maxieport');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('22', '2', 'Purdymouth');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('23', '3', 'Lake Cyrus');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('24', '4', 'New Ignatiustown');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('25', '5', 'New Bridieburgh');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('26', '6', 'Lake Marcelluschester');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('27', '7', 'Aurorefurt');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('28', '8', 'Port Willismouth');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('29', '9', 'Lilyanberg');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('30', '10', 'Sanfordbury');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('31', '11', 'Maceytown');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('32', '12', 'Murphyfurt');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('33', '13', 'Port Orland');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('34', '14', 'South Myles');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('35', '15', 'Renemouth');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('36', '16', 'New Rickeyville');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('37', '17', 'South Brooksstad');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('38', '18', 'Handstad');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('39', '19', 'South Okeyland');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('40', '20', 'Romaineview');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('41', '1', 'Blandaberg');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('42', '2', 'Bernierberg');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('43', '3', 'Port Darrin');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('44', '4', 'New Jamel');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('45', '5', 'East Joanny');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('46', '6', 'New Einarview');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('47', '7', 'West Jensen');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('48', '8', 'Trentonburgh');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('49', '9', 'DuBuquefurt');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('50', '10', 'Cleoborough');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('51', '11', 'Gusikowskitown');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('52', '12', 'North Yolandaberg');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('53', '13', 'South Brockville');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('54', '14', 'Watersbury');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('55', '15', 'North Maryjaneshire');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('56', '16', 'Lake Wilford');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('57', '17', 'Lake Donald');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('58', '18', 'South Jammie');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('59', '19', 'North Jennifer');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('60', '20', 'Port Barney');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('61', '1', 'West Clovisland');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('62', '2', 'Lake Jorge');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('63', '3', 'Alishafurt');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('64', '4', 'Samshire');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('65', '5', 'Maiyaton');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('66', '6', 'New Hermanhaven');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('67', '7', 'Heidishire');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('68', '8', 'East Joanneland');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('69', '9', 'Ziemannberg');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('70', '10', 'North Eleonore');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('71', '11', 'Dulceview');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('72', '12', 'Doylehaven');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('73', '13', 'Stehrstad');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('74', '14', 'East Wilfredside');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('75', '15', 'Port Marlinmouth');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('76', '16', 'South Brendon');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('77', '17', 'Amiramouth');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('78', '18', 'Jewellland');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('79', '19', 'Brennaborough');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('80', '20', 'West Vada');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('81', '1', 'East Justineville');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('82', '2', 'Oberbrunnermouth');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('83', '3', 'Ullrichstad');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('84', '4', 'Port Roosevelt');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('85', '5', 'Lake Bell');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('86', '6', 'Maureenbury');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('87', '7', 'Ephraimshire');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('88', '8', 'Gavinport');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('89', '9', 'Devinstad');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('90', '10', 'Mossieshire');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('91', '11', 'Lake Kennyhaven');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('92', '12', 'Cristbury');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('93', '13', 'Vergiefort');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('94', '14', 'East Brethaven');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('95', '15', 'South Hailee');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('96', '16', 'West Destinfort');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('97', '17', 'Tessview');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('98', '18', 'East Emmet');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('99', '19', 'Port Cheyenne');
INSERT INTO `settlements` (`id`, `region_id`, `name`) VALUES ('100', '20', 'New Parker');
